<div class="modal fade cm-drawer" id="cm-person-drawer" tabindex="-1" role="dialog" aria-labelledby="cm-person-title"><div class="modal-dialog"><div class="modal-content">
<div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="{{ __('committee::committee.ux.close') }}">×</button><h2 class="modal-title" id="cm-person-title">{{ __('committee::committee.ux.who_add') }}</h2></div>
<div class="modal-body"><div class="alert hidden cm-person-feedback" role="status" aria-live="polite"></div>
<ul class="nav nav-pills" role="tablist">@foreach(['office','code','external'] as $index=>$source)<li role="presentation" class="{{ $index === 0 ? 'active' : '' }}"><a href="#cm-person-{{ $source }}" data-toggle="tab" data-source="{{ $source }}" role="tab" aria-controls="cm-person-{{ $source }}" aria-selected="{{ $index === 0 ? 'true' : 'false' }}">{{ __('committee::committee.ux.source_'.$source) }}</a></li>@endforeach</ul>
<form class="cm-person-form" method="post" action="{{ route('committee.command.seat',$c->id) }}">@csrf<input type="hidden" name="person_flow" value="1"><input type="hidden" name="person_source" value="office"><input type="hidden" name="holder_kind" value="PERSON"><input type="hidden" name="order_id" value="{{ $workingOrder['id'] ?? '' }}"><input type="hidden" name="from_date" value="{{ $c->effective_from }}">
<div class="tab-content">
    <section class="tab-pane active" role="tabpanel" id="cm-person-office"><label for="cm-person-search">{{ __('committee::committee.ux.search_people') }}</label><input id="cm-person-search" type="search" class="form-control cm-people-search"><div class="cm-actions"></div>@include('committee::field',['name'=>'user_id','label'=>'ux.person','options'=>[],'class'=>'cm-people','required'=>true])</section>
    <section class="tab-pane" role="tabpanel" id="cm-person-code"><p class="cm-subtle">{{ __('committee::committee.ux.code_help') }}</p>@include('committee::field',['name'=>'verification_code','required'=>true])<button class="btn btn-primary cm-lookup-person" type="button">{{ __('committee::committee.search') }}</button><div class="cm-code-person cm-subtle hidden" role="status"></div><input type="hidden" name="user_id" class="cm-code-user"></section>
    <section class="tab-pane" role="tabpanel" id="cm-person-external"><p class="cm-subtle">{{ __('committee::committee.ux.external_help') }}</p>@foreach(['full_name_bn','full_name_en','designation_bn','designation_en','organization_name_bn','organization_name_en'] as $field)@include('committee::field',['name'=>$field,'required'=>true])@endforeach @include('committee::field',['name'=>'organization_kind','options'=>$enumOptions('UNIVERSITY GOVERNMENT AUTONOMOUS PRIVATE_EXPERT DEVELOPMENT_PARTNER OTHER')])</section>
</div>
<div class="cm-new-seat-fields"><div class="row"><div class="col-sm-7">@include('committee::field',['name'=>'seat_role_code','label'=>'ux.role','options'=>$roles->mapWithKeys(fn ($r) => [$r->code=>$display::text($r->name_bn,$r->name_en)])->all()])</div><div class="col-sm-5">@include('committee::field',['name'=>'seat_no','label'=>'ux.position','type'=>'number','value'=>($view->seats ? max(array_column($view->seats,'number')) : 0)+1,'required'=>true])</div></div>
<label class="cm-by-post-label"><input class="cm-by-post" type="checkbox"> {{ __('committee::committee.ux.by_post') }}</label><div class="cm-post-fields hidden">@include('committee::field',['name'=>'post_title_bn'])@include('committee::field',['name'=>'post_title_en'])<p class="cm-muted">{{ __('committee::committee.ux.by_post_help') }}</p></div></div>
<div class="cm-actions"><x-gov-action ability="committee.manage" type="submit" :locked="!$workingOrder" class="btn btn-primary">{{ __('committee::committee.ux.yes_add') }}</x-gov-action><button class="btn btn-default" type="button" data-dismiss="modal">{{ __('committee::committee.cancel') }}</button></div>
</form><p class="cm-muted">{{ __('committee::committee.ux.lookup_privacy') }}</p></div>
</div></div></div>
