@if($mode === 'types')
<div class="cm-actions">@foreach($types as $type)<a class="btn btn-default" href="{{ route('committee.types',['type'=>$type->id]) }}">{{ $display::text($type->name_bn,$type->name_en) }}</a>@endforeach<a class="btn btn-default" href="{{ route('committee.types',['type'=>'new']) }}">{{ __('committee::committee.new') }}</a></div>
@php
    $t = request('type') === 'new' ? null : ($types->firstWhere('id',(int)request('type')) ?? $types->first());
    $copy = $t && !$t->owner_company_id && (request('copy') || !auth()->user()->isSuperUser());
    $p = $t?->composition_policy ?? ['strength'=>['min'=>3,'max'=>5],'secretary'=>['min'=>0],'external'=>['min'=>0,'outside'=>'office'],'technical_expert'=>['min'=>0],'quorum'=>['min_present'=>2],'max_term_months'=>12,'declaration_required'=>false];
@endphp
<form class="cm-command cm-catalog cm-type-rules" data-type="{{ $t?->id }}" method="post" action="{{ $t && !$copy ? route('committee.command.type.update',$t->id) : route('committee.command.type') }}" @if($t && !$copy) data-method="PUT" @endif>@csrf
<div class="row"><section class="col-md-8"><div class="box"><h2>{{ $t ? $display::text($t->name_bn,$t->name_en) : __('committee::committee.new') }}</h2>
@if($copy)<p class="alert alert-info">{{ __('committee::committee.ux.copy_ministry') }}</p>@endif
@if($t)<input type="hidden" name="code" value="{{ $t->code }}">@else @include('committee::field',['name'=>'code','label'=>'code_label','required'=>true])@endif
<input type="hidden" name="scope" value="{{ $t && !$copy && !$t->owner_company_id ? 'national' : 'ministry' }}">
<details @if(!$t) open @endif><summary>{{ __('committee::committee.ux.committee_identity') }}</summary>@include('committee::field',['name'=>'name_bn','value'=>$t?->name_bn,'required'=>true])@include('committee::field',['name'=>'name_en','value'=>$t?->name_en,'required'=>true])@include('committee::field',['name'=>'category','options'=>$enumOptions('inventory disposal audit other'),'value'=>$t?->category])@include('committee::field',['name'=>'default_term_basis','label'=>'term_basis','options'=>$enumOptions('FISCAL_YEAR FIXED UNTIL_FURTHER_ORDER SINGLE_MATTER'),'value'=>$t?->default_term_basis])</details>
<div class="cm-rule-sentence"><span>{{ __('committee::committee.ux.rule_strength') }}</span>@include('committee::field',['name'=>'composition_policy[strength][min]','label'=>'min_strength','type'=>'number','value'=>$p['strength']['min'],'required'=>true])<span>{{ __('committee::committee.ux.rule_strength_to') }}</span>@include('committee::field',['name'=>'composition_policy[strength][max]','label'=>'max_strength','type'=>'number','value'=>$p['strength']['max'],'required'=>true])<span>{{ __('committee::committee.ux.rule_members') }}</span></div>
<input type="hidden" name="composition_policy[strength][odd_only]" value="0"><label><input type="checkbox" name="composition_policy[strength][odd_only]" value="1" @checked($p['strength']['odd_only'] ?? false)> {{ __('committee::committee.odd_only') }}</label>
<div class="cm-rule-sentence"><fieldset><legend>{{ __('committee::committee.presiding_roles') }}</legend><input type="hidden" name="composition_policy[presiding][exactly]" value="1">@foreach(['chairperson','convener'] as $roleCode)<label><input type="checkbox" name="composition_policy[presiding][roles][]" value="{{ $roleCode }}" @checked(in_array($roleCode,$p['presiding']['roles'] ?? ['chairperson','convener']))> {{ $display::text($roles->firstWhere('code',$roleCode)?->name_bn,$roles->firstWhere('code',$roleCode)?->name_en) }}</label>@endforeach</fieldset></div>
<div class="cm-rule-sentence"><span>{{ __('committee::committee.ux.rule_secretary') }}</span>@include('committee::field',['name'=>'composition_policy[secretary][min]','label'=>'secretary_min','type'=>'number','value'=>$p['secretary']['min'],'required'=>true])<input type="hidden" name="composition_policy[secretary][max]" value="{{ $p['secretary']['max'] ?? 1 }}"></div>
<div class="cm-rule-sentence"><span>{{ __('committee::committee.ux.rule_external') }}</span>@include('committee::field',['name'=>'composition_policy[external][min]','label'=>'external_min','type'=>'number','value'=>$p['external']['min'],'required'=>true])<span>{{ __('committee::committee.ux.rule_external_end') }}</span>@include('committee::field',['name'=>'composition_policy[external][outside]','label'=>'outside','options'=>$enumOptions('office ministry'),'value'=>$p['external']['outside']])</div>
@foreach(['strength','presiding','secretary','external','technical_expert'] as $rule)<details><summary>{{ __('committee::committee.ux.rule_reason') }} · {{ __('committee::committee.ux.rule_'.$rule.'_name') }}</summary>@foreach(['bn','en'] as $language)@include('committee::field',['name'=>'composition_policy['.$rule.'][reason_'.$language.']','label'=>'ux.rule_reason_'.$language,'type'=>'textarea','value'=>$p[$rule]['reason_'.$language] ?? ''])@endforeach</details>@endforeach
@foreach($p['incompatible_duties'] ?? [] as $dutyIndex=>$duty)<div class="cm-subtle"><p>{{ __('committee::committee.ux.rule_duty') }} <strong>{{ __('tenantops::access.role_names.'.$duty['duty']) }}</strong></p><input type="hidden" name="composition_policy[incompatible_duties][{{ $dutyIndex }}][duty]" value="{{ $duty['duty'] }}">@include('committee::field',['name'=>'composition_policy[incompatible_duties]['.$dutyIndex.'][severity]','label'=>'incompatible_duties','options'=>$enumOptions('WARN BLOCK'),'value'=>$duty['severity']])@foreach(['bn','en'] as $language)@include('committee::field',['name'=>'composition_policy[incompatible_duties]['.$dutyIndex.'][reason_'.$language.']','label'=>'ux.rule_reason_'.$language,'type'=>'textarea','value'=>$duty['reason_'.$language] ?? ''])@endforeach</div>@endforeach
<div class="cm-rule-sentence"><span>{{ __('committee::committee.ux.rule_term') }}</span>@include('committee::field',['name'=>'composition_policy[max_term_months]','label'=>'max_term','type'=>'number','value'=>$p['max_term_months'] ?? null])<span>{{ __('committee::committee.ux.rule_months') }}</span></div>
<details><summary>{{ __('committee::committee.ux.more_rules') }}</summary>
@foreach(app(\GovStore\Committee\Contracts\ScopeTypeRegistry::class)->keys() as $scopeType)<label><input type="checkbox" name="allowed_scope_types[]" value="{{ $scopeType }}" @checked(in_array($scopeType,$t?->allowed_scope_types ?? ['office','store']))> {{ __('committee::committee.options.'.$scopeType) }}</label>@endforeach
<input type="hidden" name="allow_concurrent" value="0"><p><label><input type="checkbox" name="allow_concurrent" value="1" @checked($t?->allow_concurrent)> {{ __('committee::committee.allow_concurrent') }}</label></p>
@include('committee::field',['name'=>'composition_policy[technical_expert][min]','label'=>'technical_min','type'=>'number','value'=>$p['technical_expert']['min'],'required'=>true])@include('committee::field',['name'=>'composition_policy[quorum][min_present]','label'=>'quorum','type'=>'number','value'=>$p['quorum']['min_present'] ?? null])@include('committee::field',['name'=>'composition_policy[nomination]','label'=>'nomination','options'=>$enumOptions('BY_POST BY_NAME BY_POST_OR_NAME'),'value'=>$p['nomination'] ?? 'BY_POST_OR_NAME'])
<input type="hidden" name="composition_policy[declaration_required]" value="0"><label><input type="checkbox" name="composition_policy[declaration_required]" value="1" @checked($p['declaration_required'])> {{ __('committee::committee.declaration_required') }}</label>
</details>
</div></section><aside class="col-md-4"><section class="box"><h2>{{ __('committee::committee.ux.rule_effect') }}</h2><p>{{ __('committee::committee.ux.rule_impact') }}</p><p class="cm-rule-impact" aria-live="polite"></p></section><section class="box">
<input type="hidden" name="is_active" value="0"><p><label><input type="checkbox" name="is_active" value="1" @checked($t?->is_active)> {{ __('committee::committee.is_active') }}</label></p>@include('committee::field',['name'=>'change_reason','type'=>'textarea','required'=>true])<x-gov-action ability="committee.types.manage" type="submit"  class="btn btn-primary btn-block">{{ __('committee::committee.save') }}</x-gov-action><p class="cm-muted">{{ __('committee::committee.policy_notice') }}</p></section></aside></div></form>
@else
@foreach($bindings->concat([null]) as $binding)
<section class="box"><h2>{{ $binding ? $display::text(collect($purposes)->first(fn ($purpose) => $purpose->code === $binding->purpose_code)?->labelBn,collect($purposes)->first(fn ($purpose) => $purpose->code === $binding->purpose_code)?->labelEn) : __('committee::committee.binding') }}</h2>
<form class="cm-command cm-catalog" action="{{ $binding ? route('committee.command.binding.update',$binding->id) : route('committee.command.binding') }}" method="post" @if($binding) data-method="PUT" @endif>@csrf
@include('committee::field',['name'=>'scope','options'=>$enumOptions('ministry national'),'value'=>$binding && !$binding->owner_company_id ? 'national' : 'ministry'])
@include('committee::field',['name'=>'purpose_code','options'=>collect($purposes)->mapWithKeys(fn ($p) => [$p->code=>$display::text($p->labelBn,$p->labelEn)])->all(),'value'=>$binding?->purpose_code])
@include('committee::field',['name'=>'committee_type_id','label'=>'type','options'=>$types->mapWithKeys(fn ($t) => [$t->id=>$display::text($t->name_bn,$t->name_en)])->all(),'value'=>$binding?->committee_type_id])
@include('committee::field',['name'=>'priority','type'=>'number','value'=>$binding?->priority ?? 0,'required'=>true])
<input type="hidden" name="allow_ancestor_fallback" value="0"><p><label><input type="checkbox" name="allow_ancestor_fallback" value="1" @checked($binding?->allow_ancestor_fallback)> {{ __('committee::committee.allow_ancestor_fallback') }}</label></p>
<input type="hidden" name="is_active" value="0"><p><label><input type="checkbox" name="is_active" value="1" @checked(!$binding || $binding->is_active)> {{ __('committee::committee.is_active') }}</label></p>
@include('committee::field',['name'=>'change_reason','type'=>'textarea','required'=>true])<x-gov-action ability="committee.purposes.manage" type="submit" class="btn btn-primary">{{ __('committee::committee.binding') }}</x-gov-action>
</form></section>@endforeach
@endif
