@extends('committee::layout')
@section('committee-content')
<header class="cm-header"><h1>{{ __('committee::committee.ux.dissolve_question') }}</h1><p class="cm-muted">{{ $display::text($c->name_bn,$c->name_en) }} · {{ $c->committee_number }}</p></header>
<section class="box"><div class="cm-subtle"><i class="fa fa-info-circle" aria-hidden="true"></i> {{ __('committee::committee.ux.lighter_alternative') }} <a class="btn btn-default" href="{{ route('committee.show',['committee'=>$c->id,'action'=>'replace']) }}">{{ __('committee::committee.ux.change_members') }}</a> <a class="btn btn-default" href="{{ route('committee.reconstitute',$c->id) }}">{{ __('committee::committee.ux.reconstitute') }}</a></div>
<div class="cm-danger"><h2>{{ __('committee::committee.ux.after_dissolve') }}</h2><ul>@foreach(app(\GovStore\Committee\Services\ImpactAnalyzer::class)->ifEnded($c->id) as $impact)<li>{{ $impact['scope'] }} · {{ $impact['purpose'] }}</li>@endforeach<li>{{ __('committee::committee.ux.members_end',['count'=>$display::digits(count($view->seats))]) }}</li><li>{{ __('committee::committee.ux.records_kept') }}</li></ul></div></section>
@include('committee::partials/working-order',['orderKind'=>'DISSOLUTION'])
<section class="box"><form class="cm-command cm-dissolve" action="{{ route('committee.command.dissolve',$c->id) }}" method="post">@csrf<input type="hidden" name="order_id" value="{{ $workingOrder['id'] ?? '' }}">@include('committee::field',['name'=>'date','type'=>'date','value'=>now('Asia/Dhaka')->toDateString(),'required'=>true])@include('committee::field',['name'=>'reason','type'=>'textarea','required'=>true])
<p><strong>{{ $c->committee_number }}</strong></p>@include('committee::field',['name'=>'confirmation','label'=>'ux.type_number','required'=>true,'class'=>'cm-dissolve-number'])<p id="cm-number-reason" class="help-block">{{ __('committee::committee.ux.type_number_help') }}</p>
<div class="cm-actions"><a class="btn btn-default" href="{{ route('committee.show',$c->id) }}">{{ __('committee::committee.cancel') }}</a><x-gov-action ability="committee.activate" type="submit" :locked="!$workingOrder" class="btn btn-danger cm-dissolve-submit" data-number="{{ $c->committee_number }}" aria-describedby="cm-number-reason">{{ __('committee::committee.ux.dissolve') }}</x-gov-action></div></form></section>
@stop
