@extends('committee::layout')
@section('committee-content')
<a class="btn btn-default" href="{{ route('committee.show',$c->id) }}">← {{ $display::text($c->name_bn,$c->name_en) }}</a>
<header class="cm-header cm-toolbar"><div><h1>{{ __('committee::committee.history') }}</h1><p class="cm-muted">{{ __('committee::committee.ux.history_intro') }}</p></div><span class="cm-status cm-status-{{ $chain ? 'block' : 'ready' }}"><i class="fa fa-{{ $chain ? 'exclamation-triangle' : 'check' }}" aria-hidden="true"></i> {{ __('committee::committee.'.($chain ? 'broken' : 'intact')) }}</span></header>
<section class="box"><h2>{{ __('committee::committee.ux.roster_on_date') }}</h2><form method="get" class="cm-actions">@include('committee::field',['name'=>'as_of','type'=>'date','value'=>$date->toDateString()])<button class="btn btn-primary" type="submit">{{ __('committee::committee.view') }}</button><a class="btn btn-default" href="{{ route('committee.print',['committee'=>$c->id,'as_of'=>$date->toDateString()]) }}">{{ __('committee::committee.print') }}</a></form>
<div class="cm-subtle"><strong>{{ $display::date($date->toDateString()) }}</strong>@foreach($view->seats as $seat)<p>{{ $display::text($roles->firstWhere('code',$seat->role)?->name_bn,$roles->firstWhere('code',$seat->role)?->name_en) }} — {{ $display::text($seat->holder?->nameBn,$seat->holder?->nameEn) ?: __('committee::committee.ux.vacant') }} <small>{{ $display::text($seat->holder?->designationBn,$seat->holder?->designationEn) }}</small></p>@endforeach</div></section>
<div class="cm-actions" role="group" aria-label="{{ __('committee::committee.ux.filter_history') }}">@foreach(['all','members','state','corrections'] as $filter)<button class="btn btn-default cm-history-filter" type="button" data-filter="{{ $filter }}" aria-pressed="{{ $filter === 'all' ? 'true' : 'false' }}">{{ __('committee::committee.ux.filter_'.$filter) }}</button>@endforeach</div>
<ol class="cm-timeline">@foreach($history->groupBy(fn ($entry) => $entry['order']['id'] ?? $entry['date']) as $group)<li class="box">@if($order = $group->first()['order'])<div class="cm-toolbar"><strong>{{ __('committee::committee.options.'.$order['kind']) }} · {{ $display::date($order['issued_on']) }}</strong>@if($order['file_url'])<a class="btn btn-default" href="{{ $order['file_url'] }}">{{ $order['memo_no'] }}</a>@endif</div>@endif
@foreach($group as $entry)<article class="cm-history-entry" data-group="{{ $entry['group'] }}"><p>{{ $entry['sentence'] }}</p><small>{{ __('committee::committee.ux.recorded_by',['name'=>$entry['actor']]) }} · {{ $entry['date'] }}</small>@if($entry['reason'])<p class="cm-muted">{{ __('committee::committee.reason') }}: {{ $entry['reason'] }}</p>@endif</article>@endforeach</li>@endforeach</ol>
<p class="cm-card cm-history-empty {{ $history->isEmpty() ? '' : 'hidden' }}" role="status">{{ __('committee::committee.ux.no_history_changes') }}</p>
@stop
