<?php

use GovStore\Committee\Http\Controllers\CommitteeController as C;
use GovStore\TenantScope\Http\Middleware\InitializeTenantContext;
use Illuminate\Support\Facades\Route;

Route::group(['prefix'=>'gov-store/committees','middleware'=>['web','auth',InitializeTenantContext::class]], function () {
    Route::get('',[C::class,'page'])->defaults('page','dashboard')->middleware('gov.can:committee.view')->name('committee.dashboard')->breadcrumbs(fn ($trail) => $trail->push(__('committee::committee.title'),route('committee.dashboard')));
    Route::get('registry',[C::class,'page'])->defaults('page','registry')->middleware('gov.can:committee.view')->name('committee.registry')->breadcrumbs(fn ($trail) => $trail->push(__('committee::committee.registry'),route('committee.registry')));
    Route::get('new',[C::class,'page'])->defaults('page','new')->middleware('gov.can:committee.manage')->name('committee.new')->breadcrumbs(fn ($trail) => $trail->push(__('committee::committee.new'),route('committee.new')));
    Route::get('transfers',[C::class,'page'])->defaults('page','transfers')->middleware('gov.can:committee.manage')->name('committee.transfers')->breadcrumbs(fn ($trail) => $trail->push(__('committee::committee.transfers'),route('committee.transfers')));
    Route::get('search',[C::class,'page'])->defaults('page','search')->middleware('gov.can:committee.view')->name('committee.search')->breadcrumbs(fn ($trail) => $trail->push(__('committee::committee.search'),route('committee.search')));
    Route::get('admin/types',[C::class,'page'])->defaults('page','types')->middleware('gov.can:committee.types.view')->name('committee.types')->breadcrumbs(fn ($trail) => $trail->push(__('committee::committee.types'),route('committee.types')));
    Route::get('admin/purposes',[C::class,'page'])->defaults('page','purposes')->middleware('gov.can:committee.purposes.view')->name('committee.purposes')->breadcrumbs(fn ($trail) => $trail->push(__('committee::committee.purposes'),route('committee.purposes')));
    Route::get('mine',[C::class,'mine'])->middleware('gov.can:committee.self')->name('committee.mine')->breadcrumbs(fn ($trail) => $trail->push(__('committee::committee.mine'),route('committee.mine')));
    Route::get('mine/tenures/{tenure}/declaration/file',[C::class,'ownDeclarationFile'])->middleware('gov.can:committee.self')->name('committee.own-declaration.file');
    Route::get('api/registry',[C::class,'registry'])->middleware('gov.can:committee.view')->name('committee.api.registry');
    Route::get('api/search',[C::class,'registry'])->middleware('gov.can:committee.view')->name('committee.api.search');
    Route::get('api/people',[C::class,'people'])->middleware('gov.can:committee.manage')->name('committee.api.people');
    Route::get('api/transfers',[C::class,'transferSeats'])->middleware('gov.can:committee.manage')->name('committee.api.transfers');
    Route::post('api/people/by-code',[C::class,'byCode'])->middleware(['gov.can:committee.manage','throttle:10,1'])->name('committee.api.by-code');
    Route::get('api/scopes/{type}',[C::class,'scopeSearch'])->middleware('gov.can:committee.manage')->name('committee.api.scopes');
    Route::get('api/coverage',[C::class,'coverageApi'])->middleware('gov.can:committee.view')->name('committee.api.coverage');
    Route::get('orders/{order}/file',[C::class,'file'])->middleware('gov.can:committee.view')->name('committee.order.file');
    Route::get('tenures/{tenure}/declaration/file',[C::class,'declarationFile'])->middleware('gov.can:committee.view')->name('committee.declaration.file');
    Route::post('drafts',[C::class,'command'])->defaults('command','create')->middleware('gov.can:committee.manage')->name('committee.command.create');
    Route::post('external-members',[C::class,'command'])->defaults('command','external')->middleware('gov.can:committee.manage')->name('committee.command.external');
    Route::post('external-members/{member}/link',[C::class,'command'])->defaults('command','link')->middleware('gov.can:committee.manage')->name('committee.command.link');
    Route::post('transfers/apply',[C::class,'command'])->defaults('command','transfer')->middleware('gov.can:committee.manage')->name('committee.command.transfer');
    Route::post('admin/types',[C::class,'command'])->defaults('command','type')->middleware('gov.can:committee.types.manage')->name('committee.command.type');
    Route::put('admin/types/{record}',[C::class,'command'])->defaults('command','type')->middleware('gov.can:committee.types.manage')->name('committee.command.type.update');
    Route::post('admin/purposes/bindings',[C::class,'command'])->defaults('command','binding')->middleware('gov.can:committee.purposes.manage')->name('committee.command.binding');
    Route::put('admin/purposes/bindings/{record}',[C::class,'command'])->defaults('command','binding')->middleware('gov.can:committee.purposes.manage')->name('committee.command.binding.update');
    Route::put('{committee}/draft',[C::class,'command'])->defaults('command','update')->middleware('gov.can:committee.manage')->name('committee.command.update');
    Route::delete('{committee}/draft',[C::class,'command'])->defaults('command','discard')->middleware('gov.can:committee.manage')->name('committee.command.discard');
    Route::post('{committee}/seats',[C::class,'command'])->defaults('command','seat')->middleware('gov.can:committee.manage')->name('committee.command.seat');
    Route::delete('{committee}/seats/{seat}',[C::class,'command'])->defaults('command','removeSeat')->middleware('gov.can:committee.manage')->name('committee.command.removeSeat');
    Route::post('{committee}/seats/{seat}/appoint',[C::class,'command'])->defaults('command','appoint')->middleware('gov.can:committee.manage')->name('committee.command.appoint');
    Route::post('{committee}/seats/{seat}/replace',[C::class,'command'])->defaults('command','replace')->middleware('gov.can:committee.manage')->name('committee.command.replace');
    Route::post('{committee}/seats/{seat}/change-draft-holder',[C::class,'command'])->defaults('command','changeDraftHolder')->middleware('gov.can:committee.manage')->name('committee.command.changeDraftHolder');
    Route::post('{committee}/tenures/{tenure}/release',[C::class,'command'])->defaults('command','release')->middleware('gov.can:committee.manage')->name('committee.command.release');
    Route::post('{committee}/tenures/{tenure}/correct',[C::class,'command'])->defaults('command','correct')->middleware('gov.can:committee.manage')->name('committee.command.correct');
    Route::post('{committee}/tenures/{tenure}/declaration',[C::class,'command'])->defaults('command','declare')->middleware('gov.can:committee.declare')->name('committee.command.declare');
    Route::post('{committee}/scopes',[C::class,'command'])->defaults('command','scope')->middleware('gov.can:committee.manage')->name('committee.command.scope');
    Route::post('{committee}/scopes/{scope}/withdraw',[C::class,'command'])->defaults('command','withdraw')->middleware('gov.can:committee.manage')->name('committee.command.withdraw');
    Route::post('{committee}/orders',[C::class,'command'])->defaults('command','order')->middleware('gov.can:committee.manage')->name('committee.command.order');
    Route::post('{committee}/reconstitute',[C::class,'command'])->defaults('command','reconstitute')->middleware('gov.can:committee.manage')->name('committee.command.reconstitute');
    Route::post('{committee}/activate',[C::class,'command'])->defaults('command','activate')->middleware('gov.can:committee.activate')->name('committee.command.activate');
    Route::post('{committee}/suspend',[C::class,'command'])->defaults('command','suspend')->middleware('gov.can:committee.activate')->name('committee.command.suspend');
    Route::post('{committee}/resume',[C::class,'command'])->defaults('command','resume')->middleware('gov.can:committee.activate')->name('committee.command.resume');
    Route::post('{committee}/extend',[C::class,'command'])->defaults('command','extend')->middleware('gov.can:committee.activate')->name('committee.command.extend');
    Route::post('{committee}/dissolve',[C::class,'command'])->defaults('command','dissolve')->middleware('gov.can:committee.activate')->name('committee.command.dissolve');
    Route::get('api/{committee}/composition',[C::class,'detailApi'])->defaults('query','composition')->middleware('gov.can:committee.view')->name('committee.api.composition');
    Route::get('api/{committee}/roster',[C::class,'detailApi'])->defaults('query','roster')->middleware('gov.can:committee.view')->name('committee.api.roster');
    Route::get('api/{committee}/impact',[C::class,'detailApi'])->defaults('query','impact')->middleware('gov.can:committee.view')->name('committee.api.impact');
    Route::get('{committee}/history',[C::class,'page'])->defaults('page','history')->middleware('gov.can:committee.view')->name('committee.history')->breadcrumbs(fn ($trail,$committee) => $trail->push(__('committee::committee.history'),route('committee.history',$committee)));
    Route::get('{committee}/print',[C::class,'page'])->defaults('page','print')->middleware('gov.can:committee.view')->name('committee.print')->breadcrumbs(fn ($trail,$committee) => $trail->push(__('committee::committee.print'),route('committee.print',$committee)));
    Route::get('{committee}/reconstitute',[C::class,'page'])->defaults('page','reconstitute')->middleware('gov.can:committee.manage')->name('committee.reconstitute')->breadcrumbs(fn ($trail,$committee) => $trail->push(__('committee::committee.reconstitute'),route('committee.reconstitute',$committee)));
    Route::get('{committee}',[C::class,'page'])->middleware('gov.can:committee.view')->name('committee.show')->breadcrumbs(fn ($trail,$committee) => $trail->push(__('committee::committee.details'),route('committee.show',$committee)));
});
